### ISSUE TITLE
Update Over WIFI

### ISSUE THREAD

**Issue by doggukan** [samdenty99/Wi-PWN#12]
http://esp8266.github.io/Arduino/versions/2.0.0/doc/ota_updates/ota_updates.html#web-browser

If you can add this option it will be super awesome.I tested this on my nodemcu with some other project installed.i went the ota update webpage selected your .bin file after 3 seconds your project was installed.Even i uploaded different project before it didnt mixed just clean wi-pwn installed without wires and computer.

**Comment by samdenty99** [comment]
Feature request has been noted and added to the [upcoming features list](https://github.com/samdenty99/Wi-PWN/projects/1#card-4322750). It should be added in V.9.0, it depends.

**Comment by doggukan** [comment]
thanks.
