### ISSUE TITLE
GPIO CAN NOT OPERATE

### ISSUE THREAD

**Issue by Buchar007** [samdenty99/Wi-PWN#13]
Czech language:
GPIO výstupy NELZE OVLÁDAT. Používám NodeMCU v3 a pokud dám HIGH nic se neděje. Podíváte se na to prosím. Děkuji.

GOOGLE TRANSLATE:
GPIO Outputs CAN NOT OPERATE. I use NodeMCU v3 and if I give HIGH nothing happens. Look, please. Thank you.

**Comment by samdenty99** [comment]
The GPIO feature is implemented, but not activated yet. It should be enabled in a future update. Consider becoming a [patron](https://www.patreon.com/samdd) or [donating](paypal.me/samd3n) to speed up development.

[**Release README:**](https://github.com/samdenty99/Wi-PWN/releases/tag/7.0)
![image](https://user-images.githubusercontent.com/13242392/29716628-eb9b2d58-89a3-11e7-8b8b-c02a94b62196.png)
