### ISSUE TITLE
Disabled_.htm

### ISSUE THREAD

**Issue by H1ghTech** [samdenty99/Wi-PWN#14]
How does this get triggered and for what is that?

**Comment by samdenty99** [comment]
The [disabled_.htm](https://wi-pwn_raw.samdd.me/web_server/html/disabled_.htm) is only a placeholder file as of right now, it's not included in the compiled binary and not accessible from within Wi-PWN. It's part of a postponed feature that hasn't been implemented. - https://github.com/samdenty99/Wi-PWN/projects/1#card-3797594
