### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by H1ghTech** [samdenty99/Wi-PWN#17]
If I select  and upload the newest .bin file it will not load the /update page

**Comment by samdenty99** [comment]
This is an issue with OTA updates, the ESP8266 has to have double the amount of storage (and sufficient memory) in order for it to successfully complete a flash. This OTA update feature is experimental and may be removed in a future commit.

As Wi-PWN needs to use the ESP8266 2.0 Arduino core, it is not possible to use the newer OTA update library.

**NOTE As you are running a beta of Wi-PWN *(It hasn't been added to the releases page)*, you may face other issues like this.**
