### ISSUE TITLE
Can u update tutorial? :)

### ISSUE THREAD

**Issue by adiif1** [samdenty99/Wi-PWN#19]
`Arduino:1.8.4 (Windows 10), Płytka:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

Wi-PWN:41: error: 'SSD1306' does not name a type

   SSD1306 display(0x3c, 5, 4); //GPIO 5 = D1, GPIO 4 = D2

   ^

C:\Users\Adiif1\Documents\Arduino\Wi-PWN-master\arduino\Wi-PWN\Wi-PWN.ino: In function 'void drawInterface()':

Wi-PWN:118: error: 'display' was not declared in this scope

     display.clear();

     ^

C:\Users\Adiif1\Documents\Arduino\Wi-PWN-master\arduino\Wi-PWN\Wi-PWN.ino: In function 'void setup()':

Wi-PWN:700: error: 'display' was not declared in this scope

   display.init();

   ^

Wi-PWN:709: error: 'ArialMT_Plain_16' was not declared in this scope

   display.setFont(ArialMT_Plain_16);

                   ^

Wi-PWN:711: error: 'ArialMT_Plain_24' was not declared in this scope

   display.setFont(ArialMT_Plain_24);

                   ^

Wi-PWN:713: error: 'ArialMT_Plain_10' was not declared in this scope

   display.setFont(ArialMT_Plain_10);

                   ^

C:\Users\Adiif1\Documents\Arduino\Wi-PWN-master\arduino\Wi-PWN\Wi-PWN.ino: In function 'void loop()':

Wi-PWN:873: error: 'display' was not declared in this scope

       display.clear();

       ^

exit status 1
'SSD1306' does not name a type

Ten raport powinien zawierać więcej informacji jeśli w 
File -> Preferencje zostanie włączona opcja "Pokaż
szczegółowe informacje podczas kompilacji"
`

**Comment by samdenty99** [comment]
Try installing the required libraries
