### ISSUE TITLE
App crashes instantly

### ISSUE THREAD

**Issue by joerie11** [samdenty99/Wi-PWN#2]
The app crashes on startup on my S7 edge

**Comment by samdenty99** [comment]
I'm aware of this issue, currently the app only runs on API version 24 (Nougat).

The app is optional and Wi-PWN can be used exactly the same without it. Open `http://192.168.4.1` in your browser as an alternative until the app is reprogrammed to work on older version of Android

**Comment by joerie11** [comment]
but as far as i know i have the newest android 7.0 nougat

**Comment by samdenty99** [comment]
Can you confirm exactly what version you're running? `Settings > About > Android Version`

**Comment by joerie11** [comment]
already told you Android-versie 7.0

**Comment by samdenty99** [comment]
The app is currently being redesigned to have support for legacy devices. This issue should be fixed in an upcoming release (either `1.3.3` or `1.4`). I've [updated the Releases page](https://github.com/samdenty99/Wi-PWN/releases/tag/1.3.2) to highlight this bug.

**Comment by joerie11** [comment]
oke

**Comment by samdenty99** [comment]
I've re-compiled the APK with support for more devices.

[**RELEASE 1.3.2B**](https://github.com/samdenty99/Wi-PWN/releases/tag/1.3.2)
[Download patched APK](https://github.com/samdenty99/Wi-PWN/releases/download/1.3.2/xOptional_Wi-PWN.apk)

**Comment by joerie11** [comment]
it works fine only i seem to miss the reboot button

**Comment by samdenty99** [comment]
I'll make sure to re-implement the button in the next update

**Comment by joerie11** [comment]
thx, You do a great job developing this
