### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by durchblicker1** [samdenty99/Wi-PWN#23]
Is it possible to implement a whitelist for mac adresses? 

Somebody wrote already a sourcecode for his own esp8266 deauther: https://github.com/RandDruid/esp8266-deauth/issues/6

**Comment by narcomerk19** [comment]
it is already presented on the current build. kindly check bro.

**Comment by durchblicker1** [comment]
Oh ok :) In v.8.0? I will check it out. Thank you

**Comment by StijnSimons** [comment]
Use the 'users' tab to scan connected mac addresses. Then select the one(s) you don't want to deauth. (Might add a 'whitelist' in a future build for people that don't want to select everyone on the users list.
