### ISSUE TITLE
Encrypted clones aren't encrypted

### ISSUE THREAD

**Issue by leperjulien** [samdenty99/Wi-PWN#25]
Hi there,

I'm using the last release on an esp8266 1.0 and everything is working perfectly except when i try to clone an AP and setup the clones to be using encryption it add them in the list and create them but all of them show as open network :/ Same bug when i use deauther8266 from spacehuhn so maybe there is no fix yet :)

**Comment by StijnSimons** [comment]
I'll look into it if i have time today.

**Comment by samdenty99** [comment]
Closing issue as no fixes have been pushed to the official repo ([spacehuhn/esp8266_deauther](https://github.com/spacehuhn/esp8266_deauther)). When / if it is fixed, the fixes will be synced with Wi-PWN
