### ISSUE TITLE
Clone button not working

### ISSUE THREAD

**Issue by xXHardGriefXx** [samdenty99/Wi-PWN#3]
As the title says. When I press clone, nothing happens.

**Comment by samdenty99** [comment]
When you click the clone button, it adds the network name to the below input field where you can then click on the add button

![image](https://user-images.githubusercontent.com/13242392/27405181-7ad1fcd6-56c8-11e7-9824-b2944a52ed14.png)

**Comment by xXHardGriefXx** [comment]
It doesnt add it to the SSID textbox.

**Comment by samdenty99** [comment]
What device are you using? Are you able to manually add networks with the SSID textbox?

**Comment by xXHardGriefXx** [comment]
I'm using the nodemcu esp8266 and yes i am able to manually add networks.

**Comment by samdenty99** [comment]
Okay, before I open a case about this can you confirm that clicking the Clone button has no effect and the input box remains the same whether you clicked the button or not?

If yes then what Operating System are you using to visit the webpage? And which browser?

**Comment by xXHardGriefXx** [comment]
Do you have teamviewer? I can show you everything haha
ID: 781 224 582
password: 9t3v9c

Awnser to your quesiton: 
The button does nothing
Im using my samsung s7 edge and the browser chrome
On my computer i have the same effect. Windows 10 and chrome

**Comment by samdenty99** [comment]
I have Teamviewer installed yes, does the online version of Wi-PWN work — https://wi-pwn.github.io/attack.html

**Comment by xXHardGriefXx** [comment]
Yes it does. And try to connect to me via the ID and password ive posted in the message before.

**Comment by samdenty99** [comment]
Issue: Special characters in network names

Patch will be released in the coming days

**Comment by samdenty99** [comment]
Just released [Version 1.4](https://github.com/samdenty99/Wi-PWN/releases/tag/1.4):
><b>..</b>
>- Bug fixes
>  - ..
>  - Single quote clone bug - Issue #3
>
><b>..</b>

I've tested it with networks that have single and double quotes in the SSIDs, let me know if the patch worked :p

**Comment by xXHardGriefXx** [comment]
Working flawlessly :)
