### ISSUE TITLE
Mobile interface issue (360x640 px)

### ISSUE THREAD

**Issue by PappleTec** [samdenty99/Wi-PWN#31]
On the Galaxy S7 there is an Issue with the "Bubbles" showing the signal strength, they are pointing to the false direction on this certain screen size.
```
>360 =  http://prntscr.com/h5dzc7 (OK)
=360 =  http://prntscr.com/h5e1a2 (ISSUE)
<360 =  http://prntscr.com/h5e1nl (OK)
```

**Comment by StijnSimons** [comment]
Has something to do in the CSS, quite sure Sam will fix this within a day

**Comment by samdenty99** [comment]
Ah yes, I'm aware of this. I had previously [asked a question on Stackoverflow](https://stackoverflow.com/questions/45355941/css-style-td-elements-depending-on-td-width) on getting the exact size when the table cells break into seperate lines, but I had use a quick JS hack (as CSS media queries can't detect the size of a DIV).

I'll try and fix this, but as there's no "fixed breaking point" it may be difficult

**Comment by StijnSimons** [comment]
Also, a resolution below 300 (i think?) breaks the reboot button.
