### ISSUE TITLE
ssid and password is not saved

### ISSUE THREAD

**Issue by kt20062011** [samdenty99/Wi-PWN#35]
ssid and password is not saved

**Comment by StijnSimons** [comment]
Maybe a bit more information than just 1 line copying the title?

**Comment by kt20062011** [comment]
I install the latest firmware version. After turning off the network settings are reset to standard. Esp-07

**Comment by kt20062011** [comment]
How to solve this problem?

**Comment by samdenty99** [comment]
Use esptool to erase the flash ~ http://www.esp8266.com/viewtopic.php?f=6&t=3955 https://diyprojects.io/esp-easy-flash-firmware-esptool-py-esp8266/
