### ISSUE TITLE
Wifi connection to slave AP for remote administration

### ISSUE THREAD

**Issue by drdeft** [samdenty99/Wi-PWN#38]
It could be very good to teach device to connect to some access point using it's WPA2 password in DHCP-client mode. Than I can forward Wi-PWN 80 port to Internet and have remote access to it.

**Comment by samdenty99** [comment]
That is possible using the [WiFi client](https://wi-pwn.samdd.me/settings) feature, though it doesn't support multiple access points.


![image](https://user-images.githubusercontent.com/13242392/33688598-e461e500-dad3-11e7-90af-e31681f85b7e.png)

**Comment by drdeft** [comment]
Wow! That's perfect project!
Will remote connection via internet work when device is in attack mode?

**Comment by samdenty99** [comment]
Unfortunately the esp can only sustain simultaneous network connections whilst in standby mode, if you wanted full remote access you'd need something like a Raspberry Pi with dual network cards

**Comment by drdeft** [comment]
I'm looking for Orange Pi to use it for automated WPS hacks. But esp8266 deauther is the first device I want to test. Unfortunately it has no built is RJ45 port with PoE support.
