### ISSUE TITLE
E5 clear client list.

### ISSUE THREAD

**Issue by mattstorm360** [samdenty99/Wi-PWN#39]
When I'm looking at the users portion of the app/webpage I'm told I need to clear the client list (E5) how do i do this?

**Comment by samdenty99** [comment]
If your running version 9.0, you can go to the info tab and hit `clearNameList.json`.

![Screenshot](https://i.imgur.com/a8h5QhZ.png)

For previous versions, simply make a GET request to the corresponding Rest API at `http://192.168.4.1`

**Example:**
```
http://192.168.4.1/clearNameList.json
```

**Comment by StijnSimons** [comment]
Can confirm that it is fixxed in 9.0 after clearing old data / memory.
