### ISSUE TITLE
Some special characters get erased when typing in a password

### ISSUE THREAD

**Issue by ramiran2** [samdenty99/Wi-PWN#40]
#,& are two of the character that get erased when i save my settings.
An example: Noob#1234 and when i save all i have left is Noob.
Version 9.0 of Wi-PWN

**Comment by samdenty99** [comment]
We are aware of this, version 9.0 has memory issues that are currently unresolved. I don't currently have the time (or the experience) to debug it, so unless someone else has experience and wants to help debug the issue, you should stick with version 8.0 (for now)
