### ISSUE TITLE
Did a translating to Polish :)

### ISSUE THREAD

**Issue by the4anoni** [samdenty99/Wi-PWN#42]
Done :)

[Polish.zip](https://github.com/samdenty99/Wi-PWN/files/1588876/Polish.zip)

**Comment by samdenty99** [comment]
Translation added! You can see it live over at [wi-pwn.samdd.me/polish](https://wi-pwn.samdd.me/polish/)

**Comment by the4anoni** [comment]
Oops... I fount a typo 
Corrected version
[Polish v2.zip](https://github.com/samdenty99/Wi-PWN/files/1589551/Polish.v2.zip)
Thanks for patience

**Comment by samdenty99** [comment]
Fixed in [`ae95a4a`](https://github.com/samdenty99/Wi-PWN/commit/ae95a4a205f0b77e1575674108d1fc61d8e108be)

**Comment by the4anoni** [comment]
But thats not all changes.
Re download file ,and check again

**Comment by samdenty99** [comment]
That is the only change though

**Comment by the4anoni** [comment]
No.
![change](https://user-images.githubusercontent.com/13403084/34388794-0a647a52-eb36-11e7-80a4-11c8057888d3.PNG)
And one more. 
Re download file

**Comment by samdenty99** [comment]
I directly downloaded and committed it, check for yourself

**Comment by the4anoni** [comment]
My mistake. Again sorry.
[Polish v3.zip](https://github.com/samdenty99/Wi-PWN/files/1589565/Polish.v3.zip)

**Comment by samdenty99** [comment]
No problem, fixed in a7a5531

**Comment by the4anoni** [comment]
Thanks for patience :)

**Comment by the4anoni** [comment]
Are U planning do 8.0 Polish version or in next version ?

**Comment by samdenty99** [comment]
The translation engine was only added in `9.0` upwards, so to test it you'll need to flash it with Arduino or wait until I upload the compiled binary to the [releases page](https://github.com/samdenty99/Wi-PWN/releases/tag/9.0)

**Comment by the4anoni** [comment]
U forgot to apply changes to demo. Also when cokpiled version will arrive ?
