### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by sam-gurdus** [samdenty99/Wi-PWN#43]
On macOS and version 8, I don't see Roboto Medium, instead I see this 
![screenshot - 0vumsw](https://user-images.githubusercontent.com/24784108/34754316-e19741e0-f571-11e7-85a9-e2d71fddb658.png)

**Comment by sam-gurdus** [comment]
Also, I was wondering what is unstable about 9.0, and when will it be fully ready? Thanks

**Comment by StijnSimons** [comment]
Had the same issue on my mac but didn't even notice it.

**Comment by StijnSimons** [comment]
At the moment, 9.0 is stable enough to use. Only problem is that you _might_ lose your currently saved SSID's and clients.
