### ISSUE TITLE
Detector Issue

### ISSUE THREAD

**Issue by ChandraOrbit** [samdenty99/Wi-PWN#44]
is there something wrong with my Device.
I have tried repeatedly Flashing against my 2 devices but the results remain the same.
When I access the Detector, it does not show any pictures at all
i am using versy 9.0  I use nodemcu V3 Lolin
Bug
![bug](https://user-images.githubusercontent.com/31229540/34905524-0b614c6e-f88d-11e7-80b3-8a246fa3b70e.png)

**Comment by edo-2313** [comment]
Compile the master branch manually and flash, there was an typo in the code
