### ISSUE TITLE
Not spamming beacons

### ISSUE THREAD

**Issue by Seldos** [samdenty99/Wi-PWN#45]
It is not creating mass beacons just 2 or 3 after a minute of waiting. It worked with the spacehuhn version

**Comment by edo-2313** [comment]
Just to be sure, did you enter some names in the list?
And are you using the beacon function or the random function?

**Comment by edo-2313** [comment]
Just to be sure, did you enter some names in the list?
And are you using the beacon function or the random function?

**Comment by StijnSimons** [comment]
Did you flash using Arduino or the .bin?

**Comment by Seldos** [comment]
Used both functions added 48 times the same name (Clone). I used both cannot properly reset arduino flashed very often and used the arduino installation until it "worked" maybe that's the reason?

**Comment by StijnSimons** [comment]
Try erasing your esp with ESPtool an reflash it.

**Comment by Seldos** [comment]
worked thank you but why didn't it work when I used a 1mb file with 0xff and wrote it at 0x0 0x1 0x2 0x3?

**Comment by StijnSimons** [comment]
Might have been a problem that the data got corrupted.
