### ISSUE TITLE
Wifi Deauther OLED V3 Board is not Compatible

### ISSUE THREAD

**Issue by ChandraOrbit** [samdenty99/Wi-PWN#49]
I did the testing 
[PWN_9.0](https://github.com/samdenty99/Wi-PWN/releases/download/9.0/Wi-PWN_9.0_ENGLISH_OLED.bin) or with [PWN_8.0](https://github.com/samdenty99/Wi-PWN/releases/download/8.0/Wi-PWN_8.0_ENGLISH_OLED.bin) with [Wifi Deauther OLED V3 Board](https://www.aliexpress.com/item/WiFi-deauther-OLED-V2-include-Case-and-Antenna/32825138910.html?spm=2114.10010108.1000013.4.3fb2ad83sZo9kj&traffic_analysisId=recommend_2088_2_90158_iswistore&scm=1007.13339.90158.0&pvid=50500de9-2d1a-4141-9caf-d33ccea3c36d&tpp=1) but not Compatible
OLED does not appear any images and Wifi SSID does not appear

Do I have to Compile & install with Arduino manually and what should be changed in its source code ?

**Comment by ChandraOrbit** [comment]
Solved .. 
Compile, change  
//create display(Adr, SDA-pin, SCL-pin)
 //SSD1306 display(0x3c, 5, 4); //GPIO 5 = D1, GPIO 4 = D2
  SH1106 display(0x3c, 5, 4); 

and Install using Flash Size 1 Mbyte

**Comment by TimSSweeney** [comment]
wait can u help me?

**Comment by TimSSweeney** [comment]
Is says those libraries can not be found

**Comment by koko004** [comment]
> Is says those libraries can not be found

Use esptool to flash bin file and set this pinout

![Wi-PWN](https://user-images.githubusercontent.com/10567364/200195166-233c14ae-1d79-4f0f-937e-d46cad790cb9.png)
