### ISSUE TITLE
buttons/shortcuts on top 

### ISSUE THREAD

**Issue by thrornnc** [samdenty99/Wi-PWN#5]
In the web interface and app, the buttons for scan, users, attack, settings isn't  showing (see screenshots).
![screenshot_2017-07-09-21-38-27](https://user-images.githubusercontent.com/28326534/27999136-b17c530a-64ef-11e7-8d21-c5e5c56a36be.png)
![screenshot_2017-07-09-21-39-07](https://user-images.githubusercontent.com/28326534/27999137-b17d55f2-64ef-11e7-99ee-8a904b570469.png)

**Comment by samdenty99** [comment]
This may be a bug relating to the Wi-PWN minimal mode. Resetting your browsers cookie should temporarily fix this. 

Minimal mode is activated by visiting `http://192.168.4.1/?minimal=true`, did you visit this link in your browser? If not, how did you get to the Wi-PWN Web UI? By directly entering the URL?

**Comment by thrornnc** [comment]
Yes, direct in url, its back! thanks.

**Comment by samdenty99** [comment]
Glad you got it fixed, if you are facing any other problems just open another issue :)
