### ISSUE TITLE
Board OLED Error E19 and E95

### ISSUE THREAD

**Issue by ChandraOrbit** [samdenty99/Wi-PWN#50]
I have done several test times on multiple boards:

1. For existing OLED boards, especially Wifi Deauther Oled V3 Board will experience errors during storage after making changes to the Settings menu, both E95 and E19 error errors.

2. For Non OLED board, error does not occur.

**Comment by freesofia** [comment]
...the same problem.

**Comment by loewal** [comment]
I also noticed, dat the ESP-01 (1 Mb. version) doesn't keep its settings. Several others do, like Wemos Lolin.
By the way:
Deauther 1.6 works perfect on my WeMos D1 ESP Wroom 02 ESP8266 NodeMcu Lua WiFi with Oled. Can you tell me why versions 8 and 9 with oled don't?

**Comment by freesofia** [comment]
I use v3.0 board, but v8 and v9 with OLED not work correctly for me!
http://prntscr.com/iin80f
