### ISSUE TITLE
Connection Resetting

### ISSUE THREAD

**Issue by sayak-brm** [samdenty99/Wi-PWN#58]
The connection is resetting for several files like `/js/functions.js` and `/main.css`, leaving the page partially rendered as shown below.
![image](https://user-images.githubusercontent.com/5992716/36533861-da363cbc-17ea-11e8-8d4f-bd7be5d1d811.png)

None of the UI elements respond.

_Tested in FireFox Quantum 58.0.2, Chrome (Android) 63.0 and the latest version of the Android Wi-Pwn App._

**Comment by loewal** [comment]
I flashed the bin, because the source doesn't compile without errors. Dsniffer....

**Comment by sayak-brm** [comment]
@loewal Wrong issue. I'm facing this issue on a 4MB NodeMCU.

For those interested, here's the network stats:
![image](https://user-images.githubusercontent.com/5992716/36534725-5f22662e-17ed-11e8-8fd6-886287abfcfe.png)

**Comment by vuong244** [comment]
https://www.hackster.io/vuong244/deauthentication-attack-with-esp8266-4ed3d3
