### ISSUE TITLE
Custom SSID Beacon Not Working?

### ISSUE THREAD

**Issue by ali6836** [samdenty99/Wi-PWN#6]
When I click the add button to add a ssid, it doesnt add a ssid?

**Comment by samdenty99** [comment]
Hey Ali, what version of Wi-PWN are you using? Can you replicate this on the [Online Interface](https://wi-pwn.github.io/attack.html)?

**Comment by ali6836** [comment]
@samdenty99 I am using version 1.5 and the same thing happens on the online interface. Below, I have attached an image that shows an error that I have noticed in the code.
<img width="1134" alt="screen shot 2017-07-16 at 20 39 48" src="https://user-images.githubusercontent.com/25329959/28250709-4200def6-6a67-11e7-8e21-23e17baea719.png">
<img width="1440" alt="screen shot 2017-07-16 at 20 39 40" src="https://user-images.githubusercontent.com/25329959/28250710-44d9a7de-6a67-11e7-89a5-0e3aa298561b.png">

**Comment by samdenty99** [comment]
Can you send dev-tool screenshots of the Web Interface? Haven't tested the software on any Apple products yet, but can you re-produce the steps that I would need to take to replicate this issue?

**Comment by samdenty99** [comment]
Found the issue, will resolve it now :)

**Comment by ali6836** [comment]
Great! How long will it take for the new release?

**Comment by samdenty99** [comment]
I'll update the current release binary in about half an hour

**Comment by ali6836** [comment]
Fantastic! Thanks for the help.

**Comment by samdenty99** [comment]
Version 1.6 will be out in a 3-7 days, the updated binary is available to [download](https://github.com/samdenty99/Wi-PWN/raw/testing/arduino/Wi-PWN/Wi-PWN.ino.nodemcu.bin) from the testing branch

**Comment by samdenty99** [comment]
[Version 6.0](https://github.com/samdenty99/Wi-PWN/releases/tag/6.0) released

> **...**
>- Fixed SSID beacon bug preventing SSIDs from being added
>- Major UI update ~
>   - Setup page redesigned, now features a cleaner design
>   - Cards have been redesigned, now feature actions at the bottom
>
> **...**
