### ISSUE TITLE
Why aren't there compiled Chinese firmware?

### ISSUE THREAD

**Issue by rfvcdewsxzaq** [samdenty99/Wi-PWN#60]
Why aren't there compiled Chinese firmware?

**Comment by samdenty99** [comment]
Because I'm too lazy to make 12 new binaries for all the translations. Feel free to compile and submit a pr

**Comment by rfvcdewsxzaq** [comment]
I am Chinese. I want a Chinese firmware. Can you compile it for me? thank you very much! Thank you!

**Comment by samdenty99** [comment]
No. Just install arduino and do it yourself

**Comment by rfvcdewsxzaq** [comment]
But I don’t know how to do it

**Comment by samdenty99** [comment]
And it's not my job to compile it for you
