### ISSUE TITLE
ESP32 Support

### ISSUE THREAD

**Issue by agucova** [samdenty99/Wi-PWN#63]
Is there any plans for supporting the ESP32?
It is significantly faster and it has been getting pretty popular lately.

**Comment by agucova** [comment]
@samdenty99 Is that a no?

**Comment by samdenty99** [comment]
https://github.com/spacehuhn/esp8266_deauther/wiki/FAQ#esp32-and-esp8285-support

**Comment by agucova** [comment]
Sorry, I didn't check that.
