### ISSUE TITLE
No documentation on what the attacks do

### ISSUE THREAD

**Issue by hussainb** [samdenty99/Wi-PWN#64]
Is there any documentation on what the attacks actually do?
For example, I do not know what the users tab does and how can it be used, is it just for information of connected users or if I can actually perform some action using it.

**Comment by samdenty99** [comment]
Nope no documentation. It should be fairly self explanatory though.

**Comment by StijnSimons** [comment]
A simple 1 minute google does everything.

**Comment by hussainb** [comment]
@StijnSimons, yes, I found it on [esp8266_deauther](https://github.com/spacehuhn/esp8266_deauther). description is available inline on the attacks page. thanks.
