### ISSUE TITLE
Random TX Power for beacon attack

### ISSUE THREAD

**Issue by Enziak** [samdenty99/Wi-PWN#69]
Hi.

It's possible to add random tx power for beacon attack like in spacehuhn project?
Thats the only code i find for it

` if (settings.getRandomTX() && (beacon.active || probe.active)) setOutputPower(random(21));
    else setOutputPower(20.5f);`

Could someone help with code and where to add it for arduino file?
Just add random tx power by default for beacon attack

**Comment by StijnSimons** [comment]
https://github.com/samdenty99/Wi-PWN/blob/master/arduino/Wi-PWN/Attack.cpp

**Comment by Enziak** [comment]
I'm still learning and can't

**Comment by Enziak** [comment]
I'm still learning and I can't manage to do that.

`C:\Users\enzo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\cores\esp8266/WString.h:113: undefined reference to `setOutputPower(float)'`

I hope it's good idea to implement and will be in next release.

**Comment by StijnSimons** [comment]
I'm not completely sure but i think the GPIO pins D0 and D1 are actually the built-in leds too.

**Comment by Enziak** [comment]
Yeah, when connected to some stronger 1A+ usb, second led above rst button can be turn on or off when i touch GPIO pins D0 and D1 (really low constant light)

No output in serial monitor and can't notice if it do something more.

**Comment by StijnSimons** [comment]
Feel free to make a pull request. Until then, i’m closing this issue as it is no longer necessary right now.
