### ISSUE TITLE
Can't connect to Wi-PWN

### ISSUE THREAD

**Issue by 3Domse3** [samdenty99/Wi-PWN#70]
As soon as I set a SSID name and a password, I can't connect to the new SSID with the correct password. I'm using the latest version of the code and the app. Also, I erased the complete flash 2x and re-flashed the ESP with the software 3x but still the same problem.

**Comment by StijnSimons** [comment]
Make sure you got the right password by going into the Serial Monitor and verifying the password.

**Comment by 3Domse3** [comment]
I got it working now by just accepting the standard SSID and pw and then manually changing it in the settings.
