### ISSUE TITLE
WI-PWN on Wemos D1 Pro Mini???

### ISSUE THREAD

**Issue by JeroenVBH** [samdenty99/Wi-PWN#73]
Hi, I succesfully uploaded Wi-PWN_9.0_ENGLISH to my Wemos D1 Pro Mini. The Blue LED is blinking just like on NodeMCU, but it doesnt show up in my wifi list. Is Wemos compatible with your code?

**Comment by digmorepaka** [comment]
Wemos is compatible, Check your flash settings. Lower the frequency to 40Mhz etc.
