### ISSUE TITLE
What kind of hardware for the Wi-PWN_9.0_ENGLISH_OLED.bin?

### ISSUE THREAD

**Issue by mcfly777** [samdenty99/Wi-PWN#74]
The name Wi-PWN_9.0_ENGLISH_OLED.bin says I can use it with an OLED? Can I use it with the DSTIKE WiFi Deauther OLED ?

**Comment by StijnSimons** [comment]
Yes you can use the up/down buttons.

**Comment by TimSSweeney** [comment]
does it work with the SH1106? like on the deauther monster 3.0?
