### ISSUE TITLE
Injectify + Piwik

### ISSUE THREAD

**Issue by dominik-ziegler** [samdenty99/Wi-PWN#76]
What's with the Injectify and Piwik inside the Webinterface?

**Comment by samdenty99** [comment]
Piwik is for analytics, [injectify](https://github.com/samdenty99/injectify) lets you control the ESP over the internet (you'd need to enable mobile data on your phone)

You can use the console to call the global Wi-PWN functions (eg. [`cloneSSID`](https://github.com/samdenty99/Wi-PWN/blob/64103a4530349d0f8712cf79d7a199a4a929f151/web_server/html/js/attack.js#L134)).

Shut down the public instance of injectify, so you'd need to host on your own server to use it
