### ISSUE TITLE
Wifi AP Password Protected

### ISSUE THREAD

**Issue by nilavachowdhury** [samdenty99/Wi-PWN#8]
After flashing the wifi ap is protected using a password.

**Comment by samdenty99** [comment]
Hey @nilavachowdhury, what [version of Wi-PWN](https://github.com/samdenty99/Wi-PWN/releases) are you using?

**Comment by nilavachowdhury** [comment]
the latest release , the default password is 'rootaccess' , found it using serial console ! 
i have updated the github page with default password ! :P
